site_name: Documentation Projet 2024 SIO2
theme:
  name: material
  custom_dir: overrides
nav:
  - index.md

  
   
  - Configuration ↳ : 
    - Access Control List: ACL.md
    - DHCP: config_dhcp_local.md
    - SSH: ssh.md
    - NAT: Nat.md
    - Création d'un vlan: vlan.md
    
  - Serveur ↳ :  
    - Serveur http: SRV-hhtp.md
    - HTTPS: https.md

  - Solutions de pare-feu ↳ : 
    - PFSense: PfSense.md
    - Firewall physique: firewall.md

  - Redondance ↳ : 
    - GLBP: glbp.md
    - HSRP: HSRP.md

  - DNS ↳ :
    - Résolver DNS: DNS_DMZ.md
    - Résolver: Redirecteur_DNS.md
    - DNS local: config_dns_local.md
      
  - Infra ↳ : 
    - Plan d'adressage: adressage.md
    - Brassage: Brassage.md 
    - Schèma logique & physique: Schema.md

