site_name: Documentation Projet 2024 SIO2
theme:
  name: material
  custom_dir: overrides
nav:
  - index.md
  - Création d'un vlan: vlan.md 
  - Configuration ↳ : 
    - Access Control List: ACL.md
    - Firewall physique: firewall.md
    - HSRP: HSRP.md
    - DHCP: config_dhcp_local.md
    - DNS: config_dns_local.md
    - SSH: ssh.md
    - GLBP: glbp.md
    - NAT: Nat.md
    
  - Infra ↳ : 
    - Plan d'adressage: adressage.md
    - Brassage: Brassage.md 
    - Schèma logique & physique: Schema.md