site_name: Documentation Projet 2024 SIO2
theme:
  name: material
  custom_dir: overrides
nav:
  - index.md
   
  - Configuration ↳ : 
    - Access Control List: ./pages/configuration/ACL.md
    - DHCP: ./pages/configuration/config_dhcp_local.md
    - SSH: ./pages/configuration/ssh.md
    - NAT: ./pages/configuration/Nat.md
    - Création d'un vlan: ./pages/configuration/vlan.md
    
  - Serveur ↳ :  
    - Serveur http: ./pages/serveur/SRV-hhtp.md
    - HTTPS: ./pages/serveur/https.md
    - Wordpress: ./pages/wordpress/conf-wp.md

  - Solutions de pare-feu ↳ : 
    - PFSense: ./pages/fw/PfSense.md
    - Firewall physique: ./pages/fw/firewall.md

  - Redondance ↳ : 
    - GLBP: ./pages/redondance/glbp.md
    - HSRP: ./pages/redondance/HSRP.md

  - DNS ↳ :
    - Résolver DNS: ./pages/dns/DNS_DMZ.md
    - Résolver: ./pages/dns/Redirecteur_DNS.md
    - DNS local: ./pages/dns/config_dns_local.md

  - Infra ↳ : 
    - Plan d'adressage: ./pages/infra/adressage.md
    - Brassage: ./pages/infra/Brassage.md 
    - Schèma logique & physique: ./pages/infra/Schema.md

