site_name: Documentation Projet 2024 SIO2
theme:
  name: material
  custom_dir: overrides
nav:
  - index.md
  - commande_md.md
  - Configuration: 
    - Plan d'adressage: adressage.md
    - Création d'un vlan: vlan.md 
    - Activation de SSH: ssh.md
    - Installation DNS: config_dns_local.md
    - Installation DHCP: config_dhcp_local.md
    - Access Control List: ACL.md
    - Firewall physique: firewall.md